version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=adscraper
      - POSTGRES_PASSWORD=adscraper
      - POSTGRES_DB=adscraper
    ports:
      - "127.0.0.1:5432:5432"
    volumes: 
      - adscraper_data:/var/lib/postgresql/data
      - ./db/adscraper.sql:/docker-entrypoint-initdb.d/create_tables.sql
    networks:
      - adscraper
volumes:
  adscraper_data:
networks:
  adscraper:
    driver: bridge